
[buildpack]
id = "org.cloudfoundry.buildpacks.php-web"
name = "PHP Web Buildpack"
version = "0.0.1"

[metadata]
default_version = "7.2.*"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"