api = "0.2"

[buildpack]
id = "org.cloudfoundry.php-web"
name = "PHP Web Buildpack"
version = "{{ .Version }}"

[metadata]
default_version = "7.2.*"
include_files = ["bin/build","bin/detect","bin/procmgr","bin/session_helper","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
