
[buildpack]
id = "org.cloudfoundry.php-web"
name = "PHP Web Buildpack"
version = "0.0.5"

[metadata]
default_version = "7.2.*"
include_files = ["bin/build","bin/detect","bin/procmgr","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
